### ISSUE TITLE
PR#54 – bundler: failed to load command: jekyll (/home/runner/work/SpaceShuttleMissionSchedule/SpaceShuttleMissionSchedule/vendor/bundle/ruby/3.3.0/bin/jekyll) /opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/psych/parser.rb:62:in `_native_parse': (/home/runner/work/SpaceShuttleMissionSchedule/SpaceShuttleMissionSchedule/_data/sedition_caucus.yml): could not find expected ':' while scanning a simple key at line 8 column 1 (Psych::SyntaxError)

### ISSUE THREAD

**Issue by RalphHightower** [RalphHightower/SpaceShuttleMissionSchedule#56]
```
bundler: failed to load command: jekyll (/home/runner/work/SpaceShuttleMissionSchedule/SpaceShuttleMissionSchedule/vendor/bundle/ruby/3.3.0/bin/jekyll)
/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/psych/parser.rb:62:in `_native_parse': (/home/runner/work/SpaceShuttleMissionSchedule/SpaceShuttleMissionSchedule/_data/sedition_caucus.yml): could not find expected ':' while scanning a simple key at line 8 column 1 (Psych::SyntaxError)
	from /opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/psych/parser.rb:62:in `parse'
	from /home/runner/work/SpaceShuttleMissionSchedule/SpaceShuttleMissionSchedule/vendor/bundle/ruby/3.3.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'

```

_Originally posted by @RalphHightower in https://github.com/RalphHightower/SpaceShuttleMissionSchedule/issues/54#issuecomment-2566485386_

**Comment by RalphHightower** [comment]
Fixed in Codespace
